version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - mrnicegyu11
      - sanderegg
    assignees:
      - sanderegg

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: weekly
    reviewers:
      - mrnicegyu11
      - pcrespov
    assignees:
      - sanderegg
