version: "3.8"
services:
  auto-deployment-agent:
    image: local/deployment-agent:${BUILD_TARGET:?build_target_required}
    build:
      context: ./
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:?build_target_required}
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "https://github.com/ITISFoundation/osparc-deployment-agent"
        org.label-schema.vcs-ref: "${VCS_REF}"
