version: "3.7"
services:
  portainer:
    image: portainer/portainer-ce
    init: true
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  auto-deployment-agent:
    image: ${DOCKER_REGISTRY}/deployment-agent:${DOCKER_IMAGE_TAG}
    init: true
    configs:
      - source: deployment_config
        target: /home/scu/config-prod.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PREFIX_STACK_NAME=${PREFIX_STACK_NAME}
      - SIMCORE_STACK_NAME=${SIMCORE_STACK_NAME}
      - SIMCORE_IMAGE_TAG=${SIMCORE_IMAGE_TAG}
      - SIMCORE_DOCKER_REGISTRY=${SIMCORE_DOCKER_REGISTRY}
      - PUBLIC_NETWORK=${PUBLIC_NETWORK}
      - MONITORED_NETWORK=${MONITORED_NETWORK}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

configs:
  deployment_config:
    file: ./${DEPLOYMENT_AGENT_CONFIG}
