version: "3.8"
services:
  auto-deployment-agent:
    image: ${DOCKER_REGISTRY}/deployment-agent:${DOCKER_IMAGE_TAG}
    init: true
    configs:
      - source: deployment_config
        target: /home/scu/config-prod.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PREFIX_STACK_NAME=${PREFIX_STACK_NAME}
      - SIMCORE_STACK_NAME=${SIMCORE_STACK_NAME}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

configs:
  deployment_config:
    file: ./${DEPLOYMENT_AGENT_CONFIG}
