name: Deployment-agent

on:
  push:
    paths-ignore:
      - "*.md"
      - "*.png"
      - "*.svg"
      - "docs/**"
      - ".vscode/**"
  pull_request:
    paths-ignore:
      - "*.md"
      - "*.png"
      - "*.svg"
      - "docs/**"
      - ".vscode/**"

jobs:
  unit-test-deployment-agent:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9]
        os: [ubuntu-20.04]
      fail-fast: false
    name: Unit-testing deployment-agent
    steps:
      - name: Exit with success
        run: exit 0

  system-test-deployment-agent:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9]
        os: [ubuntu-20.04]
      fail-fast: false
    name: System-testing deployment-agent
    steps:
      - name: Exit with success
        run: exit 0
